/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const SectorId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sector' : SectorId,
  'advantages' : IDL.Vec(IDL.Text),
  'disadvantages' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
});
export const Sector = IDL.Record({
  'id' : SectorId,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProductsByPriceRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsBySector' : IDL.Func([SectorId], [IDL.Vec(Product)], ['query']),
  'getSectors' : IDL.Func([], [IDL.Vec(Sector)], ['query']),
  'searchProductsByName' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const SectorId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sector' : SectorId,
    'advantages' : IDL.Vec(IDL.Text),
    'disadvantages' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
  });
  const Sector = IDL.Record({
    'id' : SectorId,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProductsByPriceRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsBySector' : IDL.Func([SectorId], [IDL.Vec(Product)], ['query']),
    'getSectors' : IDL.Func([], [IDL.Vec(Sector)], ['query']),
    'searchProductsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };